<?php
/**
 * Created by PhpStorm.
 * User: aslikeyou
 * Date: 7/21/15
 * Time: 23:59
 */

namespace VK;


use Exception;
use Psr\Http\Message\ResponseInterface;

class VkErrorException extends VKException
{
    protected $_response;
    /**
     * (PHP 5 &gt;= 5.1.0)<br/>
     * Construct the exception. Note: The message is NOT binary safe.
     *
     * @link http://php.net/manual/en/exception.construct.php
     *
     * @param string    $message  [optional] The Exception message to throw.
     * @param int       $code     [optional] The Exception code.
     * @param Exception $previous [optional] The previous exception used for the exception chaining. Since 5.3.0
     */
    public function __construct(
        ResponseInterface $response,
        $message = "",
        $code = 0,
        Exception $previous = null
    ) {
        $this->_response = $response;
        parent::__construct($message, $code,
            $previous); // TODO: Change the autogenerated stub
    }
}